#pragma once

class ProtocolMaker
{
public:
	static unsigned short MakeProtocol(unsigned short type1, unsigned short type2)
	{
		unsigned short usProtocol = 0;
		usProtocol |= (unsigned short)(type1 << 8);
		usProtocol |= (unsigned short)(type2 & 0x00FF);
		return usProtocol;
	}
	static unsigned char GetSegment(unsigned short usProtocol)
	{
		return (unsigned char)(usProtocol >> 8);
	}
	static unsigned char GetType(unsigned short usProtocol)
	{
		return (unsigned char)(usProtocol & 0x00FF);
	}
};
typedef ProtocolMaker _PM;

enum ProtocolSegment
{
	Seg_Game_Actor	= 1,
	Seg_Game_User	= 2,
	Seg_Game_User_Currency	= 3,
	Seg_Game_User_Inventory	= 4,
	Seg_Game_User_Quest	= 5,
	Seg_Game_Vehicle	= 6,
	Seg_Login_User	= 7,
	Seg_Main_Chat	= 8,
	Seg_Main_Game	= 9,
	Seg_Main_Login	= 10,
	
	Seg_Max
};
typedef ProtocolSegment _PS;

enum EGameActorType
{
	Inf_PlayerAppear_G2U	= 1,
	Inf_NpcAppear_G2U	= 2,
	Inf_IOAppear_G2U	= 3,
	Inf_BrickAppear_G2U	= 4,
	Inf_APAppear_G2U	= 5,
	Inf_SOAppear_G2U	= 6,
	Inf_ElevatorAppear_G2U	= 7,
	Inf_MonorailAppear_G2U	= 8,
	Inf_TardisAppear_G2U	= 9,
	Inf_FloatingBoardAppear_G2U	= 10,
	Inf_VehicleAppear_G2U	= 11,
	Inf_SecretDialogAppear_G2U	= 12,
	Inf_ActorDisappear_G2U	= 13,
	Inf_ActorDied_G2U	= 14,
	Inf_ChangeHP_G2U	= 15,
	Inf_ChangeWalkSpeed_G2U	= 16,
	Inf_ChangeSpeed_G2U	= 17,
	Req_Revive_U2G	= 18,
	Ack_Revive_G2U	= 19,
	Inf_Revive_G2U	= 20,
	Inf_ClientDirectSync_G2U	= 21,
	Req_TriggerEvent_U2G	= 22,
	Ack_TriggerEvent_G2U	= 23,
	Req_SkipSequence_U2G	= 24,
	Ack_SkipSequence_G2U	= 25,
	Inf_PlayerLevelActionSequence_G2U	= 26,
	Inf_TriggerDisable_G2U	= 27,
	Inf_UsedTriggerList_G2U	= 28,
	Inf_Warp_G2U	= 29,
	Req_Cheat_U2G	= 30,
	Ack_Cheat_G2U	= 31,
	Req_ChangePreset_U2G	= 32,
	Ack_ChangePreset_G2U	= 33,
	Inf_ChangePreset_G2U	= 34,
	Req_BeginDance_U2G	= 35,
	Ack_BeginDance_G2U	= 36,
	Req_EndDance_U2G	= 37,
	Ack_EndDance_G2U	= 38,
	Req_ChangeDanceStep_U2G	= 39,
	Ack_ChangeDanceStep_G2U	= 40,
	Inf_ChangeDanceStep_G2U	= 41,
	Req_BeginTalking_U2G	= 42,
	Ack_BeginTalking_G2U	= 43,
	Req_EndTalking_U2G	= 44,
	Ack_EndTalking_G2U	= 45,
	Req_SocialAction_U2G	= 46,
	Ack_SocialAction_G2U	= 47,
	Inf_SocialAction_G2U	= 48,
	Req_Unoccupy_IO_U2G	= 49,
	Ack_Unoccupy_IO_G2U	= 50,
	Req_SuggestCheers_U2G	= 51,
	Ack_SuggestCheers_G2U	= 52,
	Inf_SuggestCheers_G2U	= 53,
	Req_AnswerCheers_U2G	= 54,
	Ack_AnswerCheers_G2U	= 55,
	Inf_AnswerCheers_G2U	= 56,
	Req_BeginCheers_U2G	= 57,
	Ack_BeginCheers_G2U	= 58,
	Inf_BeginCheers_G2U	= 59,
	Req_CancelCheers_U2G	= 60,
	Ack_CancelCheers_G2U	= 61,
	Inf_CancelCheers_G2U	= 62,
	Req_SpeechBubble_U2G	= 63,
	Ack_SpeechBubble_G2U	= 64,
	Inf_SpeechBubble_G2U	= 65,
	Req_SetFocusedAID_U2G	= 66,
	Ack_SetFocusedAID_G2U	= 67,
	Inf_SetFocusedAID_G2U	= 68,
	Req_VoiceMessage_U2G	= 69,
	Ack_VoiceMessage_G2U	= 70,
	Inf_VoiceMessage_G2U	= 71,
	Req_VoiceChat_U2G	= 72,
	Ack_VoiceChat_G2U	= 73,
	Inf_VoiceChat_G2U	= 74,
	Req_SetLanguageType_U2G	= 75,
	Ack_SetLanguageType_G2U	= 76,
	Inf_SetLanguageType_G2U	= 77,
	Req_AgreeToSecretDialog_U2G	= 78,
	Ack_AgreeToSecretDialog_G2U	= 79,
	Inf_AgreeToSecretDialog_G2U	= 80,
	Cmd_AgreeToSecretDialog_G2U	= 81,
	Rpt_AgreeToSecretDialog_U2G	= 82,
	Req_EndOfSecretDialog_U2G	= 83,
	Ack_EndOfSecretDialog_G2U	= 84,
	Inf_EndOfSecretDialog_G2U	= 85,
	Req_SecretDialogInfo_U2G	= 86,
	Ack_SecretDialogInfo_G2U	= 87,
	Req_DBSaveAnswerToNpc_U2G	= 88,
	Ack_DBSaveAnswerToNpc_G2U	= 89,
	Req_LifeEventReward_U2G	= 90,
	Ack_LifeEventReward_G2U	= 91,
	Req_RegistSpeaker_U2G	= 92,
	Ack_RegistSpeaker_G2U	= 93,
	Inf_RegistSpeaker_G2U	= 94,
	Req_DeregistSpeaker_U2G	= 95,
	Ack_DeregistSpeaker_G2U	= 96,
	Inf_DeregistSpeaker_G2U	= 97,
	Req_ReleaseListener_U2G	= 98,
	Ack_ReleaseListener_G2U	= 99,
	Inf_ReleaseListener_G2U	= 100,
	Req_VideoChatList_U2G	= 101,
	Ack_VideoChatList_G2U	= 102,
	Req_BeginVideoChat_U2G	= 103,
	Ack_BeginVideoChat_G2U	= 104,
	Inf_BeginVideoChat_G2U	= 105,
	Req_Agree2BeginVideoChat_U2G	= 106,
	Ack_Agree2BeginVideoChat_G2U	= 107,
	Inf_Agree2BeginVideoChat_G2U	= 108,
	Req_EndVideoChat_U2G	= 109,
	Ack_EndVideoChat_G2U	= 110,
	Inf_EndVideoChat_G2U	= 111,
	Inf_ChangeAPState_G2U	= 112,
	Req_MicAnimation_U2G	= 113,
	Ack_MicAnimation_G2U	= 114,
	Inf_MicAnimation_G2U	= 115,
	Req_RegistVideoSpeaker_U2G	= 116,
	Ack_RegistVideoSpeaker_G2U	= 117,
	Inf_RegistVideoSpeaker_G2U	= 118,
	Req_DeregistVideoSpeaker_U2G	= 119,
	Ack_DeregistVideoSpeaker_G2U	= 120,
	Inf_DeregistVideoSpeaker_G2U	= 121,
	Req_BroadcastTestPacket_U2G	= 122,
	Ack_BroadcastTestPacket_G2U	= 123,
	Inf_BroadcastTestPacket_G2U	= 124,
	Inf_SekaiItemInfo_G2U	= 125,
	Inf_SekaiCurrencyInfo_G2U	= 126,
};

enum EGameUserCurrencyType
{
	Inf_UpdateCurrency_G2U	= 1,
};

enum EGameUserInventoryType
{
	Req_EquipItem_U2G	= 1,
	Ack_EquipItem_G2U	= 2,
	Req_UnEquipItem_U2G	= 3,
	Ack_UnEquipItem_G2U	= 4,
	Req_RegisterEquipmentSlot_U2G	= 5,
	Ack_RegisterEquipmentSlot_G2U	= 6,
	Req_UnRegisterEquipmentSlot_U2G	= 7,
	Ack_UnRegisterEquipmentSlot_G2U	= 8,
	Inf_ChangeEquipment_G2U	= 9,
	Inf_ChangeCostume_G2U	= 10,
	Inf_AddItem_G2U	= 11,
	Inf_DeleteItem_G2U	= 12,
	Inf_UpdateItemCount_G2U	= 13,
	Req_DiscardItem_U2G	= 14,
	Ack_DiscardItem_G2U	= 15,
	Req_UseItem_U2G	= 16,
	Ack_UseItem_G2U	= 17,
	Req_ArrangeInteriorItem_U2G	= 18,
	Ack_ArrangeInteriorItem_G2U	= 19,
	Req_RemoveInteriorItem_U2G	= 20,
	Ack_RemoveInteriorItem_G2U	= 21,
};

enum EGameUserQuestType
{
	Req_ProgressQuestList_U2G	= 1,
	Ack_ProgressQuestList_G2U	= 2,
	Req_CompleteQuestList_U2G	= 3,
	Ack_CompleteQuestList_G2U	= 4,
	Req_AcceptQuest_U2G	= 5,
	Ack_AcceptQuest_G2U	= 6,
	Req_CompletableQuest_U2G	= 7,
	Ack_CompletableQuest_G2U	= 8,
	Req_CompleteQuest_U2G	= 9,
	Ack_CompleteQuest_G2U	= 10,
	Req_CompleteQuestTask_U2G	= 11,
	Ack_CompleteQuestTask_G2U	= 12,
	Inf_CompleteQuestTask_G2U	= 13,
	Inf_UpdateQuestTask_G2U	= 14,
	Inf_ForcedQuestComplete_G2U	= 15,
	Inf_ForcedQuestGiveUp_G2U	= 16,
};

enum EGameUserType
{
	Req_EnterGame_U2G	= 1,
	Ack_EnterGame_G2U	= 2,
	Inf_KickUser_G2U	= 3,
	Req_LogoutUser_U2G	= 4,
	Ack_LogoutUser_G2U	= 5,
	Req_MoveToLab_U2G	= 6,
	Ack_MoveToLab_G2U	= 7,
	Req_PlayerList_U2G	= 8,
	Ack_PlayerList_G2U	= 9,
	Req_SelectPlayerName_U2G	= 10,
	Ack_SelectPlayerName_G2U	= 11,
	Req_CreatePlayer_U2G	= 12,
	Ack_CreatePlayer_G2U	= 13,
	Req_DeletePlayer_U2G	= 14,
	Ack_DeletePlayer_G2U	= 15,
	Req_SelectPlayer_U2G	= 16,
	Ack_SelectPlayer_G2U	= 17,
	Req_ReserveMap_U2G	= 18,
	Ack_ReserveMap_G2U	= 19,
	Req_ExitMap_U2G	= 20,
	Ack_ExitMap_G2U	= 21,
	Req_EnterMap_U2G	= 22,
	Ack_EnterMap_G2U	= 23,
	Req_ReadyToPlay_U2G	= 24,
	Ack_ReadyToPlay_G2U	= 25,
	Inf_ReserveMapForGroup_G2U	= 26,
	Req_EntryInfo_U2G	= 27,
	Ack_EntryInfo_G2U	= 28,
	Inf_EntryInfo_Item_G2U	= 29,
	Req_PlayerMove_U2G	= 30,
	Ack_PlayerMove_G2U	= 31,
	Inf_PlayerMove_G2U	= 32,
	Req_PlayerStop_U2G	= 33,
	Ack_PlayerStop_G2U	= 34,
	Inf_PlayerStop_G2U	= 35,
	Inf_NpcMove_G2U	= 36,
	Req_UseSkill_U2G	= 37,
	Ack_UseSkill_G2U	= 38,
	Inf_UseSkill_G2U	= 39,
	Req_GuardBreak_U2G	= 40,
	Ack_GuardBreak_G2U	= 41,
	Inf_GuardBreak_G2U	= 42,
	Req_SuccessToShield_U2G	= 43,
	Ack_SuccessToShield_G2U	= 44,
	Inf_SuccessToShield_G2U	= 45,
	Req_HitResult_U2G	= 46,
	Ack_HitResult_G2U	= 47,
	Inf_HitResult_G2U	= 48,
	Req_SuccessToAvoid_U2G	= 49,
	Ack_SuccessToAvoid_G2U	= 50,
	Inf_SuccessToAvoid_G2U	= 51,
	Req_ActorMoveToPos_U2G	= 52,
	Ack_ActorMoveToPos_G2U	= 53,
	Inf_ActorMoveToPos_G2U	= 54,
	Inf_ActorMoveStop_G2U	= 55,
	Req_SyncDynamicMoveLocation_U2G	= 56,
	Ack_SyncDynamicMoveLocation_G2U	= 57,
	Inf_SyncDynamicMoveLocation_G2U	= 58,
	Req_BeginSkill_U2G	= 59,
	Ack_BeginSkill_G2U	= 60,
	Inf_BeginSkill_G2U	= 61,
	Req_EndSkill_U2G	= 62,
	Ack_EndSkill_G2U	= 63,
	Inf_EndSkill_G2U	= 64,
	Inf_SetTarget_G2U	= 65,
	Req_BeginInteraction_U2G	= 66,
	Ack_BeginInteraction_G2U	= 67,
	Inf_BeginInteraction_G2U	= 68,
	Req_StopInteraction_U2G	= 69,
	Ack_StopInteraction_G2U	= 70,
	Inf_StopInteraction_G2U	= 71,
	Req_EndInteraction_U2G	= 72,
	Ack_EndInteraction_G2U	= 73,
	Inf_EndInteraction_G2U	= 74,
	Inf_NpcDialog_G2U	= 75,
	Inf_ActorCCState_G2U	= 76,
	Inf_ActorWarp_G2U	= 77,
	Inf_BeginBuff_G2U	= 78,
	Inf_EndBuff_G2U	= 79,
	Inf_DotBuff_G2U	= 80,
	Req_CallADA_U2G	= 81,
	Ack_CallADA_G2U	= 82,
	Req_PlayerWarp_U2G	= 83,
	Ack_PlayerWarp_G2U	= 84,
	Inf_BeginNpcHook_G2U	= 85,
	Inf_EndNpcHook_G2U	= 86,
	Req_DynamicMove_U2G	= 87,
	Ack_DynamicMove_G2U	= 88,
	Inf_DynamicMove_G2U	= 89,
	Req_BeginLadder_U2G	= 90,
	Ack_BeginLadder_G2U	= 91,
	Req_MoveLadder_U2G	= 92,
	Ack_MoveLadder_G2U	= 93,
	Req_EndLadder_U2G	= 94,
	Ack_EndLadder_G2U	= 95,
	Req_CancelLadder_U2G	= 96,
	Ack_CancelLadder_G2U	= 97,
	Req_BeginFall_U2G	= 98,
	Ack_BeginFall_G2U	= 99,
	Inf_BeginFall_G2U	= 100,
	Req_EndFallen_U2G	= 101,
	Ack_EndFallen_G2U	= 102,
	Inf_EndFallen_G2U	= 103,
	Req_SyncHMD_U2G	= 104,
	Ack_SyncHMD_G2U	= 105,
	Inf_SyncHMD_G2U	= 106,
	Inf_BattleState_G2U	= 107,
	Req_BeginVoiceCommand_U2G	= 108,
	Ack_BeginVoiceCommand_G2U	= 109,
	Req_EndVoiceCommand_U2G	= 110,
	Ack_EndVoiceCommand_G2U	= 111,
};

enum EGameVehicleType
{
	Inf_TransportState_G2U	= 1,
	Req_GetTransport_U2G	= 2,
	Ack_GetOnTransport_G2U	= 3,
	Inf_GetOnTransport_G2U	= 4,
	Req_GetOffTransport_U2G	= 5,
	Ack_GetOffTransport_G2U	= 6,
	Inf_GetOffTransport_G2U	= 7,
	Inf_CompleteWarp_G2U	= 8,
	Inf_GroupWarpTimerCount_G2U	= 9,
	Inf_GroupWarpStop_G2U	= 10,
	Req_PlayerMoveInTransport_U2G	= 11,
	Ack_PlayerMoveInTransport_U2G	= 12,
	Inf_PlayerMoveInTransport_G2U	= 13,
	Req_PlayerStopInTransport_U2G	= 14,
	Ack_PlayerStopInTransport_G2U	= 15,
	Inf_PlayerStopInTransport_G2U	= 16,
	Inf_ActorMoveStopInVehicle_G2U	= 17,
	Req_GetOnMW_U2G	= 18,
	Ack_GetOnMW_G2U	= 19,
	Inf_GetOnMW_G2U	= 20,
	Req_GetOffMW_U2G	= 21,
	Ack_GetOffMW_G2U	= 22,
	Inf_GetOffMW_G2U	= 23,
	Req_PlayerMoveInMW_U2G	= 24,
	Ack_PlayerMoveInMW_G2U	= 25,
	Inf_PlayerMoveInMW_G2U	= 26,
	Req_PlayerStopInMW_U2G	= 27,
	Ack_PlayerStopInMW_G2U	= 28,
	Inf_PlayerStopInMW_G2U	= 29,
	Inf_ActorMoveStopInMW_G2U	= 30,
	Req_SpawnVehicle_U2G	= 31,
	Ack_SpawnVehicle_G2U	= 32,
	Req_UnspawnVehicle_U2G	= 33,
	Ack_UnspawnVehicle_G2U	= 34,
	Req_GetOnVehicle_U2G	= 35,
	Ack_GetOnVehicle_G2U	= 36,
	Inf_GetOnVehicle_G2U	= 37,
	Req_AgreeToBoard_U2G	= 38,
	Ack_AgreeToBoard_G2U	= 39,
	Cmd_AgreeToBoard_G2U	= 40,
	Rpt_AgreeToBoard_U2G	= 41,
	Req_GetOffVehicle_U2G	= 42,
	Ack_GetOffVehicle_G2U	= 43,
	Inf_GetOffVehicle_G2U	= 44,
	Req_BeginBrake_U2G	= 45,
	Ack_BeginBrake_G2U	= 46,
	Inf_BeginBrake_G2U	= 47,
	Req_EndBrake_U2G	= 48,
	Ack_EndBrake_G2U	= 49,
	Inf_EndBrake_G2U	= 50,
	Req_Acceleration_U2G	= 51,
	Ack_Acceleration_G2U	= 52,
	Inf_Acceleration_G2U	= 53,
	Req_Steering_U2G	= 54,
	Ack_Steering_G2U	= 55,
	Inf_Steering_G2U	= 56,
	Req_BeHorning_U2G	= 57,
	Ack_BeHorning_G2U	= 58,
	Inf_BeHorning_G2U	= 59,
	Req_UpdateExterior_U2G	= 60,
	Ack_UpdateExterior_G2U	= 61,
	Inf_UpdateExterior_G2U	= 62,
	Inf_CancelOnBoard_G2U	= 63,
	Req_SyncPhysicsforce_U2G	= 64,
	Ack_SyncPhysicsforce_G2U	= 65,
	Inf_SyncPhysicsforce_G2U	= 66,
};

enum ELoginUserType
{
	Req_LoginUser_U2L	= 1,
	Ack_LoginUser_L2U	= 2,
	Req_ReserveUser_U2L	= 3,
	Ack_ReserveUser_L2U	= 4,
	Inf_KickUser_L2U	= 5,
};

enum EMainChatType
{
	Req_RegisterChatServerInMainServer_C2M	= 1,
	Ack_RegisterChatServerInMainServer_M2C	= 2,
	Req_DeregisterChatServerInMainServer_C2M	= 3,
	Ack_DeregisterChatServerInMainServer_M2C	= 4,
};

enum EMainGameType
{
	Req_RegisterGameServerInMainServer_G2M	= 1,
	Ack_RegisterGameServerInMainServer_M2G	= 2,
	Req_DeregisterGameServerInMainServer_G2M	= 3,
	Ack_DeregisterGameServerInMainServer_M2G	= 4,
	Req_EnterGame_G2M	= 5,
	Ack_EnterGame_M2G	= 6,
	Req_LogoutUser_G2M	= 7,
	Ack_LogoutUser_M2G	= 8,
	Cmd_KickUser_M2G	= 9,
	Rpt_KickUser_G2M	= 10,
	Req_SysBuildMap_G2M	= 11,
	Ack_SysBuildMap_M2G	= 12,
	Req_ChangeMapState_G2M	= 13,
	Ack_ChangeMapState_M2G	= 14,
	Req_DestroySysBuildMap_G2M	= 15,
	Ack_DestroySysBuildMap_M2G	= 16,
	Cmd_DestroyMap_M2G	= 17,
	Rpt_DestroyMap_G2M	= 18,
	Req_ReserveMap_G2M	= 19,
	Ack_ReserveMap_M2G	= 20,
	Cmd_CreateMapForPlayer_M2G	= 21,
	Rpt_CreateMapForPlayer_G2M	= 22,
	Req_ReserveMapForGroup_G2M	= 23,
	Ack_ReserveMapForGroup_M2G	= 24,
	Cmd_CreateMapForGroup_M2G	= 25,
	Rpt_CreateMapForGroup_G2M	= 26,
	Req_ExitMap_G2M	= 27,
	Ack_ExitMap_M2G	= 28,
	Req_EnterMap_G2M	= 29,
	Ack_EnterMap_M2G	= 30,
	Inf_ChangeSekaiSystemState_M2G	= 31,
	Req_SekaiSystemInfo_G2M	= 32,
	Ack_SekaiSystemInfo_M2G	= 33,
	Inf_SekaiItemInfo_M2G	= 34,
	Inf_SekaiCurrencyInfo_M2G	= 35,
	Req_Cheat_SekaiSystemSettlement_G2M	= 36,
	Ack_Cheat_SekaiSystemSettlement_M2G	= 37,
};

enum EMainLoginType
{
	Req_RegisterLoginServerInMainServer_L2M	= 1,
	Ack_RegisterLoginServerInMainServer_M2L	= 2,
	Req_DeregisterLoginServerInMainServer_L2M	= 3,
	Ack_DeregisterLoginServerInMainServer_M2L	= 4,
	Req_LoginUser_L2M	= 5,
	Ack_LoginUser_M2L	= 6,
	Req_LogoutUser_L2M	= 7,
	Ack_LogoutUser_M2L	= 8,
	Req_ReserveUser_L2M	= 9,
	Ack_ReserveUser_M2L	= 10,
	Cmd_KickUser_M2L	= 11,
	Rpt_KickUser_L2M	= 12,
};


